[env:xiao-mainline]
platform = espressif32 @ 6.12.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions\packrat_ota.csv
build_src_filter =
  +<*>
  -<ble_smoke_test.cpp>
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  h2zero/NimBLE-Arduino @ ^2.3.6

[env:wroom-mainline]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions\packrat_ota.csv
build_src_filter =
  +<*>
  -<ble_smoke_test.cpp>
build_flags =
  -DCORE_DEBUG_LEVEL=3
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  h2zero/NimBLE-Arduino @ ^2.3.6

[env:xiao-lab]
platform = espressif32 @ 6.12.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_src_filter =
  -<*>
  +<ble_smoke_test.cpp>
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  h2zero/NimBLE-Arduino @ ^2.3.6
